### ISSUE TITLE
Is v1 still suggested?

### ISSUE THREAD

**Issue by offa** [jojomatik/sync-branch#8]
**Is your feature request related to a problem? Please describe.**
/

**Describe the solution you'd like**
To know whether it's time to update or not.

**Describe alternatives you've considered**
/

**Additional context**
The docs suggest `v1`, but there's a `v2` already.

**Comment by jojomatik** [comment]
Thanks for opening the issue. I use `v2` exclusively in all my active projects, so I'd recommend anyone to switch to `v2` as well.

I've updated the readme. If you find another reference to the old version, feel free to reopen this issue :)

**Comment by offa** [comment]
Perfect, thanks! :+1:
